version: "3.9"
services:

  prueba-imagen:
    image: prueba-imagen
    container_name: prueba_tecnica_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    networks:
      - prueba_network

    depends_on:
      - mysql



  mysql:
    image: mysql
    container_name: mysql_databases
    environment:
      MYSQL_DATABASE: prueba
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    ports:
      - "3306:3306"

    networks:
      - prueba_network

    volumes:
      - mysql-volume:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: yourpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - prueba_network


networks:
  prueba_network:

volumes:
  mysql-volume: